### PR TITLE
Fix wrong type in AntiCaptcha task

### PR DESCRIPTION
**Pull request by Laiteux**
Was causing a crash when trying to submit a RecaptchaV2Enterprise task

(:

### CODE REVIEW

**Comment by Laiteux** [comment]
Hope you're doing well mate! ❤️ 

Do you think you'd be able to push this to NuGet rq btw? (:

**Comment by openbullet** [comment]
I can do it tonight

**Comment by openbullet** [comment]
Done https://www.nuget.org/packages/CaptchaSharp/1.0.12

**Comment by Laiteux** [comment]
Much appreciated, thank you! mwah

**Comment by Laiteux** [comment]
@openbullet oops, it seems like you messed something up with the JSON serialization because once upgrading to 1.0.12 the JSON-serialized request data becomes PascalCased, making the API return an error.

**Comment by openbullet** [comment]
Hey, I will make sure to check that tomorrow, sorry for the trouble. I was away over the weekend.

**Comment by openbullet** [comment]
Sorry @Laiteux, I had built and packed some stuff that I was working on and I didn't stash from my local git branch. That's what I get for not having an automated CI/CD for this 😅 I should set one up soon. Anyways the new one is going online right now, please let me know if it works now! Thanks

https://www.nuget.org/packages/CaptchaSharp/1.0.13

**Comment by Laiteux** [comment]
Hahah, no worries! Yep, seems to work know! Thanks again (:

**Pull request merged**
